services:

  db:
    image: postgres:17
    container_name: task-manager-db
    environment:
      POSTGRES_DB: task_manager
      POSTGRES_USER: task_manager
      POSTGRES_PASSWORD: task_manager
    ports:
      - "5432:5432"
    volumes:
      - task-manager_postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: task-manager-api
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/task_manager
      DB_USERNAME: task_manager
      DB_PASSWORD: task_manager
    depends_on:
      - db

volumes:

  task-manager_postgres_data:
    external: true