spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/task_manager}
spring.datasource.username=${DB_USERNAME:task_manager}
spring.datasource.password=${DB_PASSWORD:task_manager}

spring.jpa.hibernate.ddl-auto=validate

spring.application.name=task-manager